### ISSUE TITLE
Mod release python script missing color conversion

### ISSUE THREAD

**Issue by ljoonal** [neos-modding-group/neos-mod-manifest#171]
The format of the color property is not documented yet, and it's tracked at https://github.com/neos-modding-group/neos-modding-group.github.io/issues/12

I think that we all can agree that it should be done with hex strings though. The mod release notification python script [currently just uses the value of the field ](https://github.com/neos-modding-group/neos-mod-manifest/blob/ad90c8ce62db368a59a8ca0ade0f27b6b292a719/gen_notif.py#L46), whereas discord expects it to be the integer representation of the hex's value. A small hex -> int conversion utility method should be added to `utils.py`, and it should be used if the mod has a color instead of the raw value.

**Comment by EIA485** [comment]
fixed this issue in #172
