### ISSUE TITLE
The discord notification workflow fails on single quote in mod description

### ISSUE THREAD

**Issue by art0007i** [neos-modding-group/neos-mod-manifest#200]
https://github.com/neos-modding-group/neos-mod-manifest/actions/runs/3790202585/jobs/6444641922#step:6:1
https://github.com/neos-modding-group/neos-mod-manifest/actions/runs/3577158302/jobs/6015832575

basically the action calls curl with some data like

```bash
curl -d '{"description":"you're"}' '***'
```

which crashes because of the single quote inside the word "you're" ends the data part of the request specified by the -d flag

I think to fix this it would be as simple as replacing all `'` with `'\''` which seems to be the escape character for quotes in bash

**Comment by ljoonal** [comment]
`\` needs to be escaped as well in addition to `'`, but yeah. The notification thing was a quick'n'dirty hack, so I'm amazed it's managed to go this long without totally breaking down x'D

**Comment by EIA485** [comment]
ive created #202 as a potential fix for this issue

**Comment by EIA485** [comment]
huh, guess github decided to auto close this issue, i reran the failed action for #198 and it failed. not sure why #200 did not fix the issue

**Comment by XDelta** [comment]
Github auto closed it because it was titled 'fixes # 202' and then merged

**Comment by Psychpsyo** [comment]
This was fixed in #205 and should probably be closed.
