### ISSUE TITLE
Add 'Last updated' time on mod list webpage

### ISSUE THREAD

**Issue by XDelta** [neos-modding-group/neos-mod-manifest#22]
Add the current date to the mod list page on generation. This could be somewhere near the top and is when the page itself was last updated with any change.

**Comment by ljoonal** [comment]
The main issue, I think, is that the @zkxs wants the master branch of the manifest repository to be protected to only allow commits merged from approved github PR's. So automatically updating that after a PR has been merged isn't possible.
There's a few ways to work around it, such as making the action run for PR's about to be merged that modified the `manifest.json` file, or storing the last updated value somewhere else.

I must ask though, couldn't you just use Github's `ETag` header for checking if the file has been modified?
Or the [Github API](https://api.github.com/repos/neos-modding-group/neos-mod-manifest/commits?path=manifest.json&page=1&per_page=1) for getting a human readable date if that's what you want?

**Comment by XDelta** [comment]
I do mean a human readable date just on the mod list web page. Not something to be part of the manifest.json itself

**Comment by XDelta** [comment]
It would be added to the github action that generates the page from the manifest.json

**Comment by ljoonal** [comment]
Ohwait, do you mean like per-mod?

**Comment by XDelta** [comment]
No just overall, when the page was last updated as a whole is my suggestion

**Comment by XDelta** [comment]
Linked issue in the gh pages repo neos-modding-group/neos-modding-group.github.io#5
