### ISSUE TITLE
schema expansion

### ISSUE THREAD

**Issue by EIA485** [neos-modding-group/neos-mod-manifest#63]
curios to hear what y'all's thoughts would be on turning the Conflicts array each version of a mod has into a dictionary of mod guid to semver version specifier

**Comment by ljoonal** [comment]
Were you thinking of having fully incompatible mods for all versions conflicting with `{"modguid": "*"}` ?

**Comment by EIA485** [comment]
yep

**Comment by zkxs** [comment]
Seems reasonable to me

**Comment by ljoonal** [comment]
To note though, later on this kind of changes could break a lot of things once/if there's external tools that rely on the format.

**Comment by EIA485** [comment]
seeing as we have no Conflicts currently in the manifest ive submitted [a pr](https://github.com/neos-modding-group/neos-modding-group.github.io/pull/8) to our docs and when that is merged il mark this as complete
